name: Python lint

on:
  push:
    branches:
      - develop-v1
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  pyanalyze:
    name: Check Python code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pip and black
        run: |
          sudo apt install python3-pip python3-setuptools -y
          pip3 install black --user
          
      - name: Run black
        run: black --check .
